### ISSUE TITLE
Typed property Salamek\Zasilkovna\Entity\ZasilkovnaBranch::$district must be string, array used

### ISSUE THREAD

**Issue by MikyWoW** [Salamek/zasilkovna#18]
Typed property Salamek\Zasilkovna\Entity\ZasilkovnaBranch::$district must be string, array used

```php
$branch = new \Salamek\Zasilkovna\Branch($apiKey, new SQLBrach($this->database));
$branch->find($id); // Must be branch ID from Slovakia or another non Czech one
```

Branches API v3 have bug when district is not set in Zasilkovna DB then it returning empty array.
```
...
"district": {},
...
```
Probably best solution is to migrate to branches API v4.

**Comment by Salamek** [comment]
This should be fixed and v4 branch api is tracked in #22
