### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mzvarik** [Salamek/zasilkovna#24]
Není tam ZPL
A jako celkově fakt maras... proč je ApiSoap a ApiRest kopie všech funkcí? Nestačilo dát jeden soubor...

**Comment by Salamek** [comment]
> Není tam ZPL

No nikdo ti nebrani ZPL implementovat a poslat PR ;-)

> A jako celkově fakt maras...

`s/maras/marast/` (`maras` je "po slovensky") To muze byt tvym omezenym pohledem na vec...

>  proč je ApiSoap a ApiRest kopie všech funkcí? Nestačilo dát jeden soubor...

_Talk is cheap. Show me the code.
Torvalds, Linus_

... ocividne jsi nad tim totiz moc nepremyslel nez jsi napsal tento "Feedback" s nulovou uzitnou hodnotou, ale i tak:

Zasilkovna ma dve API rozhrani jedno implementujci `SOAP` a druhe `REST` rozhrani, proto dva soubory implementujci SOAP a REST rozhrani.. muzes pouzit jedno nebo druhe, nechapu co je za problem.

**Comment by mzvarik** [comment]
no dobře :D jak se říká... darovanému koni na zuby nehleď.. tak tedy děkuji :)

**Comment by Salamek** [comment]
V pohode, je to komunitni projekt... prispet muze kazdy :)
