### ISSUE TITLE
'mixed' parameter type used but package still supported for PHP >= 7.4

### ISSUE THREAD

**Issue by patrik-owly** [Salamek/zasilkovna#25]
`mixed` parameter type only for PHP >= 8.0

https://github.com/Salamek/zasilkovna/blob/1e29fb4ee2c8ed78d57c46595ec99c666f59e0db/src/Exception/PacketAttributesFault.php#L13

But package requires PHP >= 7.4:
https://github.com/Salamek/zasilkovna/blob/1e29fb4ee2c8ed78d57c46595ec99c666f59e0db/composer.json#L25

**Comment by Salamek** [comment]
Debian 11 still uses PHP 7.4 so i guess removing mixed type from [PacketAttributesFault.php](https://github.com/Salamek/zasilkovna/blob/1e29fb4ee2c8ed78d57c46595ec99c666f59e0db/src/Exception/PacketAttributesFault.php#L13) would be a best way of action?
