### ISSUE TITLE
Type hint mixed. 

### ISSUE THREAD

**Issue by vzikmund** [Salamek/zasilkovna#29]
Hi, 
I am using your package (version 3.1.3) which should be able to run on php 7.4 according to your docs  and composer.json `php: >=7.4.0`.

However in the file `Tool.php` you are using `mixed` type hint, which was introduced in PHP 8.0 (https://php.watch/versions/8.0/mixed-type) https://github.com/Salamek/zasilkovna/blob/8846427a8800dcdd891ab6e2480dc3611dbcaff9/src/Tool.php#L14

Is this a bug or feature? 🙃

**Comment by dasim** [comment]
Same problem here, running it on PHP 7.4 raises this problem. 
`Argument 1 passed to Salamek\Zasilkovna\Tool::convertToString must be an instance of Salamek\Zasilkovna\mixed, null given`

**Comment by Salamek** [comment]
Ok ok!, i have removed that in 3.1.4, but the second Debian 12 is released as stable, i'm flooding this project with PHP 8.1 stuff lol

**Comment by vzikmund** [comment]
Wow. Thank you for such a prompt fix 🙏

**Comment by dasim** [comment]
Thanks
