### ISSUE TITLE
Undefined index: nameStreet

### ISSUE THREAD

**Issue by vzikmund** [Salamek/zasilkovna#30]
Hello, 
in `ZasilkovnaBranch::__construct()` you are trying to access value by key `nameStreet`.  

https://github.com/Salamek/zasilkovna/blob/35c81dd4c1864ed0b9d4dd53094d0862d3feee8c/src/Entity/ZasilkovnaBranch.php#L72

However the API is not returning key `nameStreet` but key `street`.

![image](https://user-images.githubusercontent.com/85373369/223375153-a3273aa4-6ad6-4e0f-8ef1-7859a9acf919.png)

**Comment by Salamek** [comment]
Hi, please check `master` branch if everything is ok and let me know... i will do proper release after

**Comment by Salamek** [comment]
@vzikmund ping

**Comment by vzikmund** [comment]
Thanks for the reminder 🙏  

The update triggered another error. In case there isn't specified parameter 'status_id', `undefined index` is thrown. I think the problem is that you are trying cast non existing `$status['statusId']` to int. There should be smth to check the existence of that key before cast is called.

![image](https://user-images.githubusercontent.com/85373369/223753537-738ba314-3e1e-49cd-b2b1-66decaad8b51.png)

**Comment by Salamek** [comment]
@vzikmund ok, that should be fixed in master

**Comment by vzikmund** [comment]
Perfect 👍 Now everything seems to be working smoothly.

**Comment by Salamek** [comment]
Great, released in 3.2
