### ISSUE TITLE
packetsLabelsPdf - input is not ideal

### ISSUE THREAD

**Issue by tomaspilat** [Salamek/zasilkovna#7]
in function 'packetsLabelsPdf'
input must be in the format:
```
[		
'__custom:id:1' => 'id1',
'__custom:id:2' => 'id2',
]
```

**Comment by janbarasek** [comment]
What input format do you suggest? Can you send a sample interface?

**Comment by haos3** [comment]
`$packetIds = [ 
    'id'` => [
        'id1',
        'id2'
    ]
]`

**Comment by Salamek** [comment]
I don't really see how this issue of this library? I can't find any docs for this input format...
DOCs does not mention it https://docs.packetery.com/03-creating-packets/06-packetery-api-reference.html#toc-packetlabelpdf

Input is just simple array[string]
```php
$packetIds = [
    "1234567890",
    "1234567891",
    "1234567892",
];
```

**Comment by patrik-owly** [comment]
Look at the XML at the link you posted to `packetsLabelsPdf` reference, there is `id` key inside of `packetIds` array
```xml
<packetsLabelsPdf>
    <apiPassword>...</apiPassword>
    <packetIds>
        <id>1234567890</id>
        <id>1234567891</id>
        <id>1234567892</id>
    </packetId>
    <format>A7 on A4</format>
    <offset>0</offset>
</packetsLabelsPdf>
```

So I'm currently using `packetsLabelsPdf` for example likes this:
```php
...

$packetIds = ['id' => []];

foreach ($orders as $order) {
	  if ($order->zasilkovnaPacketId !== null) {
			$packetIds['id'][] = $order->zasilkovnaPacketId;
	  }
}

$content = $this->zasilkovnaClient->api->packetsLabelsPdf($packetIds, $format, $offset);

...
```

**Comment by Salamek** [comment]
@Patrik-K2D Aha now it makes more sense, so changing https://github.com/Salamek/zasilkovna/blob/ef070b6f419a67984d22e8369d4027ec2458e2af/src/ApiRest.php#L167 to:

```php
return $this->callApi(__FUNCTION__, ['packetIds' => ['id' => $packetIds], 'format' => $format, 'offset' => $offset]);
```

should do it?

**Comment by patrik-owly** [comment]
Yes, this will solve this issue.
